meta:
  title: Compiler Log
  author: alcxpr

site:
  origin: https://alcxpr.github.io/blog
  view_transitions: true

rss:
  enabled: true
  title: Compiler Log
  description: Blog & Notes
  collection: blog

design:
  inline_css: true

collections:
  blog:
    include: [blog/posts/]
    require: [title]
    sort: date desc
