meta:
  title: Compiler Log
  author: alcxpr

site:
  origin: https://alcxpr.dev/
  view_transitions: true

header:
  branding:
    - text: alcxpr
      url: /

  social:
    - image: /icon/github.svg
      url: https://github.com/alcxpr
      alt: GitHub
      class: social-link

rss:
  enabled: true
  title: Compiler Log
  description: Blog & Notes
  collection: blog

design:
  inline_css: true

collections:
  blog:
    include: [posts/]
    require: [title]
    sort: date desc
